# Generated by Django 3.2.3 on 2021-06-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=32)),
            ],
        ),
    ]
